apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-despachos-deployment
  namespace: innovatech-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-despachos
  template:
    metadata:
      labels:
        app: backend-despachos
    spec:
      containers:
      - name: backend-despachos
        # Usa la variable de cuenta que configuramos en el pipeline
        image: 966929335910.dkr.ecr.us-east-1.amazonaws.com/innovatech-backend-despachos:latest
        ports:
        - containerPort: 8080
        env:
        # AGREGADO: Forzar a Hibernate a crear tablas faltantes automáticamente
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        # SOLUCIÓN: Cambiamos valueFrom por el valor directo en texto (value)
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-despachos-service:5432/db_despachos"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres" # <--- O escribe aquí el usuario real de tu Postgres si no es 'postgres'
        # Inyección automática desde el Secret seguro de GitHub
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: innovatech-db-secrets
              key: POSTGRES_DESPACHOS_PASSWORD
        - name: SERVER_PORT
          value: "8080"