apiVersion: v1
kind: Service
metadata:
  name: backend-despachos-service
  namespace: innovatech
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend-despachos