version: '3.8'

services:
  # Base de datos Ventas
  postgres-ventas:
  build:
    context: ./database
    #image: postgres:16
    container_name: postgres-ventas
    restart: always
    environment:
      - POSTGRES_DB=ventas_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_ventas_data:/var/lib/postgresql/data
      - ./database/ventas-init.sql:/docker-entrypoint-initdb.d/ventas-init.sql
    networks:
      - innovatech-network

  # Base de datos Despachos
  postgres-despachos:
    build:
      context: ./database
      #image: postgres:16
      container_name: postgres-despachos
      restart: always
      environment:
        - POSTGRES_DB=despachos_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_despachos_data:/var/lib/postgresql/data
      - ./database/despachos-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - innovatech-network

  # Backend Ventas (Descarga directa desde Docker Hub)
  backend-ventas:
   build:
    context: ./back-Ventas_SpringBoot/Springboot-API-REST
    #image: separdx/innovatech-backend-ventas:latest
    container_name: backend-ventas
    restart: always
    depends_on:
      - postgres-ventas
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-ventas:5432/ventas_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - BACKEND_DESPACHOS_HOST=backend-despachos
      - SERVER_PORT=8080
    ports:
      - "8081:8080"
    networks:
      - innovatech-network

  # Backend Despachos (Descarga directa desde Docker Hub)
  backend-despachos:
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
      #image: separdx/innovatech-backend-despachos:latest
    container_name: backend-despachos
    restart: always
    depends_on:
      - postgres-despachos
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-despachos:5432/despachos_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8080
    ports:
      - "8082:8080"
    networks:
      - innovatech-network

  # Frontend Despacho (Descarga directa desde Docker Hub)
  frontend-despacho:
    build:
      context: ./front_despacho
      #image: separdx/innovatech-frontend:latest
    container_name: frontend-despacho
    restart: always
    depends_on:
      - backend-ventas
      - backend-despachos
    ports:
      - "80:80"
    networks:
      - innovatech-network

volumes:
  postgres_ventas_data:
  postgres_despachos_data:

networks:
  innovatech-network:
    driver: bridge