# =========================================================
# CONFIGURACIÓN DEL SERVIDOR SPRING BOOT
# =========================================================

# Puerto interno del contenedor.
# Docker Compose expone este puerto como 8081.
server.port=${SERVER_PORT:8081}

# =========================================================
# CONFIGURACIÓN BASE DE DATOS POSTGRESQL
# =========================================================

# URL de conexión hacia PostgreSQL.
# "postgres-ventas" es el nombre del servicio definido
# dentro de docker-compose.yml.
spring.datasource.url=${SPRING_DATASOURCE_URL}

# Usuario de PostgreSQL.
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}

# Contraseña de PostgreSQL.
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Driver JDBC PostgreSQL.
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================================================
# =========================================================
# CONFIGURACIÓN JPA / HIBERNATE
# =========================================================

# Hibernate SOLO valida la estructura existente.
# NO crea tablas automáticamente.
spring.jpa.hibernate.ddl-auto=validate

# Muestra consultas SQL en consola.
spring.jpa.show-sql=true

# Formatea SQL mostrado en consola.
spring.jpa.properties.hibernate.format_sql=true

# Desactiva Open Session In View.
# Mejora rendimiento y arquitectura.
spring.jpa.open-in-view=false