apiVersion: v1
kind: Secret
metadata:
  name: innovatech-db-secrets
  namespace: innovatech-v2
type: Opaque
stringData:
  # Kubernetes inyectará automáticamente los secretos que configuramos en GitHub
  POSTGRES_VENTAS_PASSWORD: "${{ secrets.POSTGRES_VENTAS_PASSWORD }}"
  POSTGRES_DESPACHOS_PASSWORD: "${{ secrets.POSTGRES_DESPACHOS_PASSWORD }}"