apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-ventas-deployment
  namespace: innovatech-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-ventas
  template:
    metadata:
      labels:
        app: postgres-ventas
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: innovatech-db-config
              key: POSTGRES_VENTAS_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: innovatech-db-config
              key: POSTGRES_VENTAS_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: innovatech-db-secrets
              key: POSTGRES_VENTAS_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-ventas-service
  namespace: innovatech
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-ventas