apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-despachos-deployment
  namespace: innovatech-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-despachos
  template:
    metadata:
      labels:
        app: postgres-despachos
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: innovatech-db-config
              key: POSTGRES_DESPACHOS_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: innovatech-db-config
              key: POSTGRES_DESPACHOS_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: innovatech-db-secrets
              key: POSTGRES_DESPACHOS_PASSWORD