apiVersion: v1
kind: Service
metadata:
  name: frontend-despachos-service
  namespace: innovatech-v2
  annotations:
  #bloqueo de seguridad para que el balanceador de carga sea accesible desde internet
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend-despachos